// <auto-generated />
namespace YachmanAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedshiptocruise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedshiptocruise));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251802464_Added ship to cruise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
