// <auto-generated />
namespace YachmanAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsersconvertedtoAppUsertoavoidconflicts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersconvertedtoAppUsertoavoidconflicts));
        
        string IMigrationMetadata.Id
        {
            get { return "202002020007549_Users converted to AppUser to avoid conflicts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
